// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_bRYFxpOr-2j-nluAMiscpp6FKvPGF9s',
    appId: '1:163378598013:web:4c7ff63195abcd69252114',
    messagingSenderId: '163378598013',
    projectId: 'store-app-df5ac',
    authDomain: 'store-app-df5ac.firebaseapp.com',
    storageBucket: 'store-app-df5ac.firebasestorage.app',
    measurementId: 'G-YZ4BQMGTZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQgmCluXUv5YST6EDhJu8BmqmyNROxOt4',
    appId: '1:163378598013:android:766f9fa9c8077cf4252114',
    messagingSenderId: '163378598013',
    projectId: 'store-app-df5ac',
    storageBucket: 'store-app-df5ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAANmZvR2NmX1BoDskLhBnk37c_k25RRBs',
    appId: '1:163378598013:ios:74c4452c41c69b2e252114',
    messagingSenderId: '163378598013',
    projectId: 'store-app-df5ac',
    storageBucket: 'store-app-df5ac.firebasestorage.app',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAANmZvR2NmX1BoDskLhBnk37c_k25RRBs',
    appId: '1:163378598013:ios:74c4452c41c69b2e252114',
    messagingSenderId: '163378598013',
    projectId: 'store-app-df5ac',
    storageBucket: 'store-app-df5ac.firebasestorage.app',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_bRYFxpOr-2j-nluAMiscpp6FKvPGF9s',
    appId: '1:163378598013:web:f6c78838dc0c9e5a252114',
    messagingSenderId: '163378598013',
    projectId: 'store-app-df5ac',
    authDomain: 'store-app-df5ac.firebaseapp.com',
    storageBucket: 'store-app-df5ac.firebasestorage.app',
    measurementId: 'G-9SK8BDS6VX',
  );

}