// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7VuOTL2t8muAHohZ1yFUsXZPHMKD37fk',
    appId: '1:181086195492:web:fbf2e848d15e0728916db1',
    messagingSenderId: '181086195492',
    projectId: 'shopyra-app',
    authDomain: 'shopyra-app.firebaseapp.com',
    storageBucket: 'shopyra-app.firebasestorage.app',
    measurementId: 'G-QNJYDCSTJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9m-pmOZOnSlfPypQsVnkSi1-m79NKRLg',
    appId: '1:181086195492:android:0f2203f03a4274a7916db1',
    messagingSenderId: '181086195492',
    projectId: 'shopyra-app',
    storageBucket: 'shopyra-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvdvnDsASSexWKotOu9H9BPKSODpyhrks',
    appId: '1:181086195492:ios:bed1da468d8cd668916db1',
    messagingSenderId: '181086195492',
    projectId: 'shopyra-app',
    storageBucket: 'shopyra-app.firebasestorage.app',
    iosBundleId: 'com.sherifshouaib.shopyra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvdvnDsASSexWKotOu9H9BPKSODpyhrks',
    appId: '1:181086195492:ios:bed1da468d8cd668916db1',
    messagingSenderId: '181086195492',
    projectId: 'shopyra-app',
    storageBucket: 'shopyra-app.firebasestorage.app',
    iosBundleId: 'com.sherifshouaib.shopyra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7VuOTL2t8muAHohZ1yFUsXZPHMKD37fk',
    appId: '1:181086195492:web:cfa63dd031dcd515916db1',
    messagingSenderId: '181086195492',
    projectId: 'shopyra-app',
    authDomain: 'shopyra-app.firebaseapp.com',
    storageBucket: 'shopyra-app.firebasestorage.app',
    measurementId: 'G-GLCRNCJCM7',
  );
}
